<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pfprojects"
 *
 * Auto generated by Extension Builder 2016-01-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'PF Projects',
    'description' => 'This extension shows a list of all masterplan projects of Pforzheim',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'projects@jweiland.net',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-6.2.99',
            'maps2' => '1.0.0-1.99.99',
            'wes_egovernment' => '1.0.0-1.99.99'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);